steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  id: backend_bucket
  args: ['replace_backend_bucket_name.bash']
- name: hashicorp/terraform:latest
  id: init 
  args: ['init']
  waitFor:
    - backend_bucket
- name: hashicorp/terraform:latest
  args: ['apply', '-auto-approve']
  waitFor:
    - init

logsBucket: 'gs://$PROJECT_ID-patching-tfstate'
options:
  logStreamingOption: STREAM_ON
  logging: GCS_ONLY

tags: ['cos']
