steps:
- name: hashicorp/terraform:latest
  id: init 
  args: ['init']
  env:
    EMAIL_ADDRESS: agnieszka.rebisz@capgemini.com
- name: hashicorp/terraform:latest
  args: ['apply', '-auto-approve']
  env:
    EMAIL_ADDRESS: agnieszka.rebisz@capgemini.com
  waitFor:
    - init

