steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'  
  args: ["./logging/scripts/add_os_types.sh"]
- name: hashicorp/terraform:latest
  id: init 
  args: ['init']
- name: hashicorp/terraform:plan
  args: ['plan']
  waitFor:
    - init
- name: hashicorp/terraform:latest
  args: ['apply', '-auto-approve']
  waitFor:
    - plan

logsBucket: 'gs://$PROJECT_ID-tfstate'
options:
  logStreamingOption: STREAM_ON
  logging: GCS_ONLY
