steps:
- name: hashicorp/terraform:latest
  id: init 
  args: ['init']
  env:
    - 'PROJECT_ID=$PROJECT_ID'
  
- name: hashicorp/terraform:latest
  args: ['apply', '-auto-approve']
  env:
    - 'PROJECT_ID=$PROJECT_ID'
  waitFor:
    - init

logsBucket: 'gs://$PROJECT_ID-tfstate'
options:
  logStreamingOption: STREAM_ON
  logging: GCS_ONLY
