steps:
- name: hashicorp/terraform:latest
  id: init 
  args: ['init']
  
- name: hashicorp/terraform:latest
  args: ['apply', '-auto-approve']
  waitFor:
    - init
substitutions:
    _EMAIL_ADDRESS: agnieszka.rebisz@capgemini.com

