steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'  
  args: ["./logging/scripts/add_os_types.sh"]
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args:
  - '-c'
  - |
  sed -i 's/%SECRET_KEY%/'${_SECRET_KEY}'/g' app.yaml

- name: hashicorp/terraform:latest
  id: init 
  args: ['init']
- name: hashicorp/terraform:latest
  args: ['apply', '-auto-approve']
  waitFor:
    - init

logsBucket: 'gs://$PROJECT_ID-patching-tfstate'
options:
  logStreamingOption: STREAM_ON
  logging: GCS_ONLY

tags: ['cos']
