variable "project_id" {}
variable "zone" {}
variable "region" {}
variable "instance_name_prefixes" {}
variable "duration" {}
variable "rollout_mode" {}
variable "rollout_disruption_budget_percentage" {}
variable "recurring_schedule" {}
variable "recurring_schedule_time_zone_id" {}
variable "recurring_schedule_time_of_day_hours" {}
variable "recurring_schedule_time_of_day_minutes" {}
variable "recurring_schedule_monthly_month_day" {}
variable "one_time_schedule_execute_time" {}
variable "patch_config_os_yum" {}
variable "one_time_patching_task" {}
